/*======================================================================

   stopnback Bezier Coordinates
   Generated By Bezier Designer
   Relminator 2010

======================================================================*/

#include "Bezier.h"


		//	Point Format:
		//	x,y



		//	Table Format:
		//	d,t

#ifndef BEZIER_STOPNBACK__H
#define BEZIER_STOPNBACK__H


#define BEZIER_STOPNBACK_NUM_ELEMENTS   32
#define BEZIER_STOPNBACK_RATE   16384
#define BEZIER_STOPNBACK_TOTAL_DISTANCE   2271993


extern Bezier::Coord bezier_stopnback_coord[4];

extern Bezier::Coord bezier_stopnback_coord_mirrored[4];

extern Bezier::Table bezier_stopnback_table[32];


#endif
