/*======================================================================

   wave Bezier Coordinates
   Generated By Bezier Designer
   Relminator 2010

======================================================================*/

#include "Bezier.h"


		//	Point Format:
		//	x,y



		//	Table Format:
		//	d,t

#ifndef BEZIER_WAVE__H
#define BEZIER_WAVE__H


#define BEZIER_WAVE_NUM_ELEMENTS   32
#define BEZIER_WAVE_RATE   16384
#define BEZIER_WAVE_TOTAL_DISTANCE   1870897


extern Bezier::Coord bezier_wave_coord[4];

extern Bezier::Coord bezier_wave_coord_mirrored[4];

extern Bezier::Table bezier_wave_table[32];


#endif
