/*======================================================================

   loop Bezier Coordinates
   Generated By Bezier Designer
   Relminator 2010

======================================================================*/

#include "Bezier.h"


		//	Point Format:
		//	x,y



		//	Table Format:
		//	d,t

#ifndef BEZIER_LOOP__H
#define BEZIER_LOOP__H


#define BEZIER_LOOP_NUM_ELEMENTS   32
#define BEZIER_LOOP_RATE   16384
#define BEZIER_LOOP_TOTAL_DISTANCE   2297853


extern Bezier::Coord bezier_loop_coord[4];

extern Bezier::Coord bezier_loop_coord_mirrored[4];

extern Bezier::Table bezier_loop_table[32];


#endif
