/*======================================================================

   circle Bezier Coordinates
   Generated By Bezier Designer
   Relminator 2010

======================================================================*/

#include "Bezier.h"


		//	Point Format:
		//	x,y



		//	Table Format:
		//	d,t

#ifndef BEZIER_CIRCLE__H
#define BEZIER_CIRCLE__H


#define BEZIER_CIRCLE_NUM_ELEMENTS   32
#define BEZIER_CIRCLE_RATE   16384
#define BEZIER_CIRCLE_TOTAL_DISTANCE   2817561


extern Bezier::Coord bezier_circle_coord[4];

extern Bezier::Coord bezier_circle_coord_mirrored[4];

extern Bezier::Table bezier_circle_table[32];


#endif
