/*======================================================================

   transpormaboss_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef TRANSPORMABOSS_SPRITE__H
#define TRANSPORMABOSS_SPRITE__H


#define TRANSPORMABOSS_SPRITE_BITMAP_WIDTH   128
#define TRANSPORMABOSS_SPRITE_BITMAP_HEIGHT  128
#define TRANSPORMABOSS_SPRITE_NUM_IMAGES   13


		//	Format:
		//	U,V,Width,Height



extern const unsigned int transpormaboss_sprite_texcoords[] = {
 0, 80, 32, 32,				// 0
 64, 0, 64, 38,				// 1
 0, 0, 64, 48,				// 2
 0, 48, 64, 32,				// 3
 48, 112, 16, 16,				// 4
 0, 112, 16, 16,				// 5
 16, 112, 16, 16,				// 6
 32, 112, 16, 16,				// 7
 32, 80, 26, 32,				// 8
 64, 48, 26, 32,				// 9
 90, 48, 26, 32,				// 10
 64, 80, 26, 32,				// 11
 90, 80, 26, 26,				// 12
};


#endif
