/*======================================================================

   viper_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef VIPER_SPRITE__H
#define VIPER_SPRITE__H


#define VIPER_SPRITE_BITMAP_WIDTH   64
#define VIPER_SPRITE_BITMAP_HEIGHT  128
#define VIPER_SPRITE_NUM_IMAGES   24


		//	Format:
		//	U,V,Width,Height



extern const unsigned int viper_sprite_texcoords[] = {
 0, 0, 32, 16,				// 0
 32, 0, 32, 16,				// 1
 0, 16, 32, 16,				// 2
 32, 16, 32, 16,				// 3
 0, 32, 32, 16,				// 4
 52, 40, 8, 8,				// 5
 20, 104, 8, 8,				// 6
 20, 112, 8, 8,				// 7
 52, 32, 8, 8,				// 8
 0, 48, 20, 20,				// 9
 20, 48, 20, 20,				// 10
 40, 48, 20, 20,				// 11
 32, 32, 20, 12,				// 12
 0, 68, 20, 12,				// 13
 20, 68, 20, 12,				// 14
 40, 68, 20, 12,				// 15
 0, 80, 20, 12,				// 16
 0, 92, 20, 12,				// 17
 0, 104, 20, 12,				// 18
 0, 116, 20, 12,				// 19
 20, 80, 20, 12,				// 20
 40, 80, 20, 12,				// 21
 20, 92, 20, 12,				// 22
 40, 92, 20, 12,				// 23
};


#endif
