/*======================================================================

   mmx_shot_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef MMX_SHOT_SPRITE__H
#define MMX_SHOT_SPRITE__H


#define MMX_SHOT_SPRITE_BITMAP_WIDTH   64
#define MMX_SHOT_SPRITE_BITMAP_HEIGHT  128
#define MMX_SHOT_SPRITE_NUM_IMAGES   4


		//	Format:
		//	U,V,Width,Height



const unsigned int mmx_shot_sprite_texcoords[] = {
 0, 0, 40, 32,				// 0
 0, 32, 40, 32,				// 1
 0, 64, 40, 32,				// 2
 0, 96, 40, 32,				// 3
};


#endif
