/*======================================================================

   gluteus_boss_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef GLUTEUS_BOSS_SPRITE__H
#define GLUTEUS_BOSS_SPRITE__H


#define GLUTEUS_BOSS_SPRITE_BITMAP_WIDTH   128
#define GLUTEUS_BOSS_SPRITE_BITMAP_HEIGHT  128
#define GLUTEUS_BOSS_SPRITE_NUM_IMAGES   7


		//	Format:
		//	U,V,Width,Height



extern const unsigned int gluteus_boss_sprite_texcoords[] = {
 0, 0, 77, 89,				// 0
 0, 89, 32, 32,				// 1
 32, 89, 32, 32,				// 2
 77, 0, 32, 32,				// 3
 77, 32, 32, 32,				// 4
 77, 64, 32, 32,				// 5
 77, 96, 32, 32,				// 6
};


#endif
