/*======================================================================

   centipede_head_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef CENTIPEDE_HEAD_SPRITE__H
#define CENTIPEDE_HEAD_SPRITE__H


#define CENTIPEDE_HEAD_SPRITE_BITMAP_WIDTH   64
#define CENTIPEDE_HEAD_SPRITE_BITMAP_HEIGHT  512
#define CENTIPEDE_HEAD_SPRITE_NUM_IMAGES   6


		//	Format:
		//	U,V,Width,Height



extern const unsigned int centipede_head_sprite_texcoords[] = {
 0, 0, 64, 64,				// 0
 0, 64, 64, 64,				// 1
 0, 128, 64, 64,				// 2
 0, 192, 64, 64,				// 3
 0, 256, 64, 64,				// 4
 0, 320, 64, 64,				// 5
};


#endif
