/*======================================================================

   vic_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef VIC_SPRITE__H
#define VIC_SPRITE__H


#define VIC_SPRITE_BITMAP_WIDTH   64
#define VIC_SPRITE_BITMAP_HEIGHT  128
#define VIC_SPRITE_NUM_IMAGES   22


		//	Format:
		//	U,V,Width,Height



extern const unsigned int vic_sprite_texcoords[] = {
 44, 72, 20, 20,				// 0
 0, 96, 20, 20,				// 1
 24, 72, 20, 20,				// 2
 48, 24, 16, 16,				// 3
 48, 48, 16, 16,				// 4
 24, 92, 16, 16,				// 5
 48, 0, 16, 16,				// 6
 0, 0, 24, 24,				// 7
 24, 0, 24, 24,				// 8
 0, 24, 24, 24,				// 9
 24, 24, 24, 24,				// 10
 0, 48, 24, 24,				// 11
 24, 48, 24, 24,				// 12
 0, 72, 24, 24,				// 13
 48, 16, 8, 8,				// 14
 56, 16, 8, 8,				// 15
 48, 40, 8, 8,				// 16
 56, 40, 8, 8,				// 17
 0, 116, 20, 12,				// 18
 40, 92, 20, 12,				// 19
 40, 104, 20, 12,				// 20
 40, 116, 20, 12,				// 21
};


#endif
