/*======================================================================

   centipede_segments_sprite coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef CENTIPEDE_SEGMENTS_SPRITE__H
#define CENTIPEDE_SEGMENTS_SPRITE__H


#define CENTIPEDE_SEGMENTS_SPRITE_BITMAP_WIDTH   32
#define CENTIPEDE_SEGMENTS_SPRITE_BITMAP_HEIGHT  512
#define CENTIPEDE_SEGMENTS_SPRITE_NUM_IMAGES   12


		//	Format:
		//	U,V,Width,Height



extern const unsigned int centipede_segments_sprite_texcoords[] = {
 0, 0, 32, 32,				// 0
 0, 32, 32, 32,				// 1
 0, 64, 32, 32,				// 2
 0, 96, 32, 32,				// 3
 0, 128, 32, 32,				// 4
 0, 160, 32, 32,				// 5
 0, 192, 32, 32,				// 6
 0, 224, 32, 32,				// 7
 0, 256, 32, 32,				// 8
 0, 288, 32, 32,				// 9
 0, 320, 32, 32,				// 10
 0, 352, 32, 32,				// 11
};


#endif
